### ISSUE TITLE
Weave HTML displays a blank preview when out_path is set

### ISSUE THREAD

**Issue by CiaranOMara** [JunoLab/language-weave#25]
Weave HTML displays a blank preview when out_path is set.

I'm setting the out_path via YAML.

```YAML
options:
    md2html:
        out_path : html
---
```

The HTML document weaves successfully and is output to the specified path. However, Atom displays a blank preview of the HTML.
